{{- if and .Values.patch.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ca-injector.fullname" . }}-patch
  labels:
    {{- include "ca-injector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 2 }}
{{- end }}
